# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "string-0.0.1-PoOZyi67AAC_6tCF0Su5Bh9Yg8zAe4v7F5Py5WfAx20P";
    path = fetchgit {
      url = "https://github.com/YetAnotherMechanicusEnjoyer/libstring";
      rev = "bbfa07aeac8af6b9a59685d819ceda2f67a1a694";
      hash = "sha256-lN+Z7Xj8FZH7bchKstbJKKQo79GnK0FzY0P/HKKljJU=";
    };
  }
]
