name: AUR Publisher

run-name: AUR Publisher | ${{ github.event_name }} by ${{ github.actor }} on '${{ github.ref_name }}'

on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

permissions:
  contents: write

jobs:
  publish-aur:
    name: Publishing to AUR
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - pkgname: wayra
          - pkgname: wayra-git

    steps:
      - name: Check Execution Context
        id: check
        run: |
          if [[ "${{ matrix.pkgname }}" == "wayra" && "${{ github.ref_type }}" == "branch" ]]; then
            echo "Ce push est sur une branche. On passe le build du paquet stable (wayra)."
            echo "This action is triggered by a push on a branch. Skipping... (${{ matrix.pkgname }})."
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Setup SSH keys
        if: steps.check.outputs.skip == 'false'
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.AUR_PRIVATE_KEY }}

      - name: Add AUR host key
        if: steps.check.outputs.skip == 'false'
        run: ssh-keyscan -H aur.archlinux.org >> ~/.ssh/known_hosts
        shell: bash

      - name: Checkout
        if: steps.check.outputs.skip == 'false'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract Git Tag version
        id: version_extract
        if: steps.check.outputs.skip == 'false'
        run: |
          if [[ "${{ matrix.pkgname }}" == "wayra" ]]; then
            VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')
          else
            if git describe --tags &> /dev/null; then
              VERSION=$(git describe --long --tags --abbrev=7 | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g')
            else
              COUNT=$(git rev-list --count HEAD)
              HASH=$(git rev-parse --short=7 HEAD)
              VERSION="0.0.0r${COUNT}.g${HASH}"
            fi
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        shell: bash

      - name: Clone AUR Repository
        if: steps.check.outputs.skip == 'false'
        run: |
          git clone ssh://aur@aur.archlinux.org/"${{ matrix.pkgname }}".git

          cd "${{ matrix.pkgname }}"

          git config user.email "servoskull@omnissiah.mars"
          git config user.name "Servo Skull"

      - name: Update PKGBUILD
        if: steps.check.outputs.skip == 'false'
        run: |
          cd "${{ matrix.pkgname }}"

          sed -i "s/^pkgver=.*/pkgver=${{ steps.version_extract.outputs.VERSION }}/" PKGBUILD

          sed -i "s/^pkgrel=.*/pkgrel=1/" PKGBUILD

          sed -i "s/^sha256sums=.*/sha256sums=('SKIP')/" PKGBUILD

          sed -i "s/^pkgname=.*/pkgname=${{ matrix.pkgname }}/" PKGBUILD

      - name: Regenerate .SRCINFO
        if: steps.check.outputs.skip == 'false'
        run: |
          cd "${{ matrix.pkgname }}"
          docker run --rm \
            -v $(pwd):/app \
            archlinux/archlinux:latest \
            /bin/bash -c "\
              pacman-key --init && \
              pacman-key --populate archlinux && \
              pacman -Syu --noconfirm base-devel && \
              useradd -m builder && \
              chown -R builder:builder /app && \
              su - builder -c 'cd /app && makepkg --printsrcinfo > .SRCINFO'"
        shell: bash

      - name: AUR Repository Permissions
        if: steps.check.outputs.skip == 'false'
        run: |
          CURRENT_USER=$(whoami)
          sudo chown -R $CURRENT_USER:$CURRENT_USER "${{ matrix.pkgname }}"/
        shell: bash

      - name: Commit and Push to AUR
        if: steps.check.outputs.skip == 'false'
        run: |
          cd "${{ matrix.pkgname }}"

          git add PKGBUILD .SRCINFO
          git commit -m "workflow: bump ${{ matrix.pkgname }} to version ${{ steps.version_extract.outputs.VERSION }}" && git push || exit 0
