name: Nix Publisher

run-name: Nix Publisher | ${{ github.event_name }} by ${{ github.actor }} on '${{ github.ref_name }}'

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  update-flake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Get version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update version in flake.nix
        run: |
          sed -i 's/version = ".*";/version = "${{ steps.get_version.outputs.version }}";/' flake.nix

      - name: Commit and push changes
        run: |
          git config user.email "servoskull@omnissiah.mars"
          git config user.name "Servo Skull"

          git add flake.nix

          git diff --quiet && git diff --staged --quiet || (git commit -m "workflow: bump flake.nix version to ${{ steps.get_version.outputs.version }}" && git push origin main)
