name: Zig CI

run-name: Zig CI | ${{ github.event_name }} by ${{ github.actor }} on '${{ github.ref_name }}'

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  actions:
    name: Zig Actions
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v4
      - uses: YetAnotherMechanicusEnjoyer/zig-actions/ci@v1
        with:
          zig-version: "0.16.0"
          command-test: "zig build test"
          failure-on-error: true
